[package]
name = "gitty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.4.11", features = ["derive"] }
compress = "0.2.1"
hex = "0.4.3"
sha1 = "0.10.6"
